[opener]
edit = [
    { run = 'micro "$@"', block = true, desc = "Edit with Micro" }
]

image = [
	{ run = "imv %s", desc = "Imv (Image viewer)" },
	{ run = "xdg-open %s", desc = "Default" }
]

[open]
rules = [
	{ mime = "image/*", use = ["image"] }
]
