#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = es  			 # Keyboard layout (change to your country code if needed)
    numlock_by_default = true   	 # Automatically enable NumLock on boot
    repeat_rate = 50            	 # Keyboard repeat rate (characters per second)
    repeat_delay = 300          	 # Delay before a held key starts repeating (ms)
    follow_mouse = 1            	 # Window focus follows mouse movement
    sensitivity = 0             	 # Mouse sensitivity (-1.0 to 1.0), 0 is default
    float_switch_override_focus = false  # Prevents floating windows from erratic focus stealing

    touchpad {
        disable_while_typing = true 	 # Prevents accidental clicks while typing
        natural_scroll = true       	 # Enables "Natural Scrolling" (mobile style)
        tap-to-click = true         	 # Enables clicking by tapping on the touchpad
    }
}


# See https://wiki.hypr.land/Configuring/Gestures

gestures {
    gesture = 3, horizontal, workspace
    workspace_swipe_distance = 500           # Distance required to complete a swipe
    workspace_swipe_invert = true            # Inverts swipe direction for a more intuitive feel
    workspace_swipe_min_speed_to_force = 30  # Minimum speed to trigger a workspace change
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_create_new = true        # Swiping past the last workspace creates a new one
    workspace_swipe_forever = true           # Allows continuous swiping through all workspaces
}


# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
